version: 2

sources:
  - name: staging
    database: ny-taxi-zoomcamp-411215
    schema: ny_taxi

    tables:
      - name: green_tripdata
      - name: ny_fhv_2019


#       What is the count of records in the model fact_fhv_trips after running all dependencies with the test run variable disabled (:false)?
# Create a staging model for the fhv data, similar to the ones made for yellow and green data. Add an additional filter for keeping only records with
#  pickup time in year 2019. Do not add a deduplication step. Run this models without limits (is_test_run: false).

# Create a core model similar to fact trips, but selecting from stg_fhv_tripdata and joining with dim_zones. Similar to what we've done in fact_trips, keep only records with known pickup and dropoff locations entries for pickup and dropoff locations. Run the dbt model without limits (is_test_run: false).

# 12998722
# 22998722
# 32998722
# 42998722
