FROM ubuntu:17.04
FROM selenium/standalone-chrome
FROM python:3.9-slim
WORKDIR /my_code
COPY src/requirements.txt /my_code
# COPY src/. /my_code
RUN pip install --upgrade pip
# RUN pip install
RUN pip install --trusted-host pypi.python.org -r requirements.txt
CMD python src/StepStone_scraper.py